### PR TITLE
AbstractRestfulController support added

### PR DESCRIPTION
**Pull request by wiktor-obrebski**
Hi, I use this module with AbstractRestfulController, not only with AbstractActionController. Simple add it fullname in array make it work with both. Maybe it is good to have this as standard?

### CODE REVIEW

**Comment by texdc** [comment]
Thanks! @EvanDotPro please approve this PR.

**Comment by EvanDotPro** [comment]
Hi @psychowico -- could you please update this to use array() instead of the 5.4 [] syntax? Thanks!

**Comment by wiktor-obrebski** [comment]
done

**Comment by Paul-PSDigital** [comment]
Hi, would recommend just going for the abstract controller class rather than listing each one?

->attach('Zend\Mvc\Controller\AbstractController', 'dispatch', function($e) {

**Comment by EvanDotPro** [comment]
@thepauleh good point.

@psychowico If you update this PR to use the AbstractController, I'll get it merged.

**Pull request merged**
